# Adapted from the .travis.yml config file and
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
branches:
  except:
    - gh-pages
    - output

image: ubuntu
services:
  - docker

install:
  - echo $APPVEYOR_PROJECT_ID
  - echo $APPVEYOR_BUILD_ID
  - echo $APPVEYOR_BUILD_NUMBER
  - echo $APPVEYOR_BUILD_VERSION
  - echo $APPVEYOR_JOB_ID
  - echo $APPVEYOR_JOB_NUMBER
  - echo $APPVEYOR_REPO_COMMIT
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config
    --set always_yes yes
    --set changeps1 no
  - conda env create --quiet --file build/environment.yml
  - conda list --name manubot
  - conda activate manubot
    
test_script:
  - bash build/build.sh

build: off

cache:
  - ci/cache

artifacts:
  - path: output/manuscript.pdf
    name: Manuscript PDF

on_success:
  - echo "Updated PDF available from https://ci.appveyor.com/api/projects/$APPVEYOR_REPO_NAME/artifacts/output/manuscript.pdf?branch=$APPVEYOR_REPO_BRANCH"