# Adapted from the .travis.yml config file and
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
skip_branch_with_pr: true

# This alone is not sufficient to avoid running AppVeyor on the
# output branch commits made by Travis CI
# Need to also specify branches to build as master only in the
# AppVeyor project settings UI
branches:
  only:
    - master

# Only build on the merge commits from a pull request branch to master
# and not on other master branch commits
# See https://www.appveyor.com/docs/how-to/filtering-commits/#include-commits
# and https://regex101.com/r/L8Uvb2/4
# This does not work as intended https://github.com/agitter/my-manuscript/pull/8
#only_commits:
#  message: /Merge \b([a-f0-9]{7,40})\b into \b([a-f0-9]{7,40})\b/

only_commits:
  files:
    - .appveyor.yml
    - content/

image: ubuntu
services:
  - docker

install:
  - source ci/install.sh
    
test_script:
  - bash build/build.sh
  - TRIGGERING_COMMIT=${APPVEYOR_PULL_REQUEST_HEAD_COMMIT:-APPVEYOR_REPO_COMMIT}
  - appveyor AddMessage "commit $TRIGGERING_COMMIT"
  - MANUSCRIPT_FILENAME=manuscript-$APPVEYOR_BUILD_VERSION-${TRIGGERING_COMMIT:0:7}.pdf
  - cp output/manuscript.pdf $MANUSCRIPT_FILENAME
  - appveyor PushArtifact $MANUSCRIPT_FILENAME

build: off

cache:
  - ci/cache

on_success:
  - echo "Artifacts available from $APPVEYOR_URL/project/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG/builds/$APPVEYOR_BUILD_ID/artifacts"
  - echo "Updated PDF available from $APPVEYOR_URL/api/buildjobs/$APPVEYOR_JOB_ID/artifacts/$MANUSCRIPT_FILENAME"

# Notifications use Mustache templates http://mustache.github.io/mustache.5.html
# See https://www.appveyor.com/docs/notifications/#customizing-message-template for available variables
notifications:
  - provider: GitHubPullRequest
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}})
      {{#jobs}}{{#messages}} ({{message}} by @{{&commitAuthorUsername}}) {{/messages}}{{/jobs}}
      {{#jobs}}{{#artifacts}}<br>Generated [{{fileName}}]({{permalink}}) for review{{/artifacts}}{{/jobs}}"
