# Adapted from the .travis.yml config file and
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
skip_branch_with_pr: true

branches:
  only:
    - master
  except:
    - gh-pages
    - output

image: ubuntu
services:
  - docker

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config
    --set always_yes yes
    --set changeps1 no
  - conda env create --quiet --file build/environment.yml
  - conda list --name manubot
  - conda activate manubot
    
test_script:
  - bash build/build.sh
  - MANUSCRIPT_FILENAME=manuscript-$APPVEYOR_BUILD_VERSION-${APPVEYOR_REPO_COMMIT:0:7}.pdf
  - echo $MANUSCRIPT_FILENAME
  - ls
  - cp output/manuscript.pdf $MANUSCRIPT_FILENAME
  - appveyor PushArtifact <file_name> $MANUSCRIPT_FILENAME

build: off

cache:
  - ci/cache

on_success:
  - echo "Artifacts available from https://ci.appveyor.com/project/$APPVEYOR_REPO_NAME/builds/$APPVEYOR_BUILD_ID/artifacts"
  - echo "Updated PDF available from https://ci.appveyor.com/api/buildjobs/$APPVEYOR_JOB_ID/artifacts/$MANUSCRIPT_FILENAME"

# Notifications use Mustache templates http://mustache.github.io/mustache.5.html
# See https://www.appveyor.com/docs/notifications/#customizing-message-template for available variables
notifications:
  - provider: GitHubPullRequest
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
      {{#jobs}}{{#artifacts}}<br>[Updated {{fileName}}]({{permalink}}){{/artifacts}}{{/jobs}}"